export const CREAT_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCES = "LOAD_COURSES_SUCCES";
export const LOAD_AUTHOR_SUCCES = "LOAD_AUTHOR_SUCCES";
export const ADD_COURSE_SUCCES = "ADD_COURSE_SUCCES";
export const UPDATE_COURSE_SUCCES = "UPDATE_COURSE_SUCCES";
